### ISSUE TITLE
Hope to add co-line instructions for Shanghai Metro style (like the co-line ends of lines 3 and 4)

### ISSUE THREAD

**Issue by NiuBoss123** [railmapgen/rmg#41]
Since Shanghai Metro Lines 3 and 4 are co-line ends, it means that the location of the co-line segment can be shown, and it can also become more effective. Here are some suggestions
1. When adding a common line segment representation to a line, it means that another line indication needs to be added, which may increase the algorithm complexity, so the indication of another line may not be needed initially, but if the file input port of another line can be added , Meaning the algorithm will be simpler (recommended)
2. Other cities have not made a collinear end statement, please also pay attention to the official website of the subway company in other cities, if there is any, you can add it as soon as possible

**Comment by wongchito** [comment]
Thanks for the suggestions. (Reference #24)

**Comment by thekingofcity** [comment]
Co-line feature is a long requesting feature and I want to share some thoughts on it.

Currently the underlying data structure has no place for the this co-line feature. To support the addtional data such as the different line and its color, some changes must be made.

## Sol 1 (Add edges at the param level)

The new data structure will look like this:
```json
const params = {
    svg_height: 330,
    padding: 2.88,
    stn_list: {
        l1mz: {
            name: ["花桥", "Huaqiao"],
            branch: {left: [], right: []},
            ...
        },
        ...
    },
    edges: [
        ['l1mz', 'sjih', {color: '#76232F', ...}],
        ...
    ],
    ...
```

We may discuss the structure of `edges` lately, but the main idea here is to transform the params to a standard [graph](https://en.wikipedia.org/wiki/Graph_(discrete_mathematics)).

> G = (V, E), where V is a set whose elements are called vertices (singular: vertex), and E is a set of paired vertices, whose elements are called edges (sometimes links or lines). 

### Pros:

* pure graph data structure
* only one location of data and is clear to maintain
* works better with invisible stations (where the co-line ends here and goes beyond the canvas)
* enable further possibility such as several lines with different services level (as we can draw line segment by segment)

### Cons:

* less compatibility with the current data structure
* need to reimplement a lot of current algorithms

## Sol 2 (Add edges inside the station)

The new data structure will look like this:
```json
const params = {
    svg_height: 330,
    padding: 2.88,
    stn_list: {
        l1mz: {
            parents: [ ["linestart", {color: '#76232F', ...}] ],
            children: [ ["sjih", {color: '#76232F', ...}], [...]],
            name: ["花桥", "Huaqiao"],
            branch: {left: [], right: []},
            ...
        },
        ...
    },
    ...
```

We may discuss the structure of `edges` lately.

This implementation adds metadata of the co-line to the existing station part.

### Pros:

* can *go faster and break less* with the maximum compatibility
* works with all the algorithms we have

### Cons:

* messy data structure
* both connecting can have the edges data and need to set a rule to maintain them

---

BTW, both sol could get rid of the `linestart` and `lineend` by specifying the start and end station.

**Comment by NiuBoss123** [comment]
Thank you very much for giving me a way to deal with it

**Comment by thekingofcity** [comment]
Hi, this issue is selected as our core feature for the next generation. We'll work on this as soon as possible.

**Comment by thekingofcity** [comment]
As we come close to the next generation development, solutions proposed earlier require a major overhaul of our underlying data structure and algorithms. To comply with the *go faster and break less* rule for the V5, let me give another solution.

## Sol 3

In this solution, we turn this feature into a virtual-only effect which means co-line data will be stored beside the current `stn_list`. Instead of changing the underlying part, all the computation is done in the `svg` component. This is would also help other style maintainers since no more change will be adapted to comply with this feature.

```typescript
        <g id="main" transform={`translate(0,${param.svg_height - 63})`}>
            <Line paths={paths} direction={param.direction} />
            <CoLine paths={paths} />
            <StationGroup xs={xs} ys={ys} stnStates={stnStates} />
            <ServicesElements
                servicesLevel={servicesPresent}
                dy={-param.svg_height + 100}
                direction={param.direction}
                lineXs={lineXs}
            />
            <DirectionElements />
        </g>
```

Basically, we will add a `CoLine` visual component between the original line and station components, and therefore new double or triple line could be placed over or next to the original line.

### Narrowing down the scope

Of course, there could dozens of situations where co-line can be operated. In this particular issue or feature, we will go into Shanghai lines 3 and 4 where co-line operates on the shared mainline and breaks into branch lines where 3 and 4 operate solely on each branch line. This means a co-line will only happen on the mainline and between two branch stations.

Other situations include co-line on mainline between arbitrary stations, co-line on the branch line, co-line goes through mainline and branch line, etc.

We may support the first two but not the third as drawing a line from the branch line to the mainline needs far more work and testing.

### Work with circle line

The co-line of Shanghai Metro involves a circle/loop line, so this should be worked with #24 as well. The new circle line feature should be able to handle the branch line, which I would like to take that part.

What I could imagine the difficulty of having branch lines on the circle line is that when we change the current station of the circle line, the branch line and stations on it will change dramatically. @wongchito 

### Implementation details

Here comes some implementation details on the new co-line feature. We will let users add segments where co-line will take place in panels. After this metadata is set, we can draw the new main co-line like what we do right now.

Currently, after we calculate the `xs` and `ys` of the stations, we split it according to `stnStates` and pass it to `_linePath` function where we draw the actual `<path>`.

In the new implementation, we still calculate all the `xs` and `ys` of the stations, but we intersect the co-line stations. So when we split and pass it to `_linePath`, there will only be co-line segments and we draw that part with new colors from metadata users previously defined in the panel.

**Comment by thekingofcity** [comment]
![image](https://user-images.githubusercontent.com/3353040/150642118-d496196b-abba-4861-a378-e2e5777441c5.png)

Some working progress.

**Comment by thekingofcity** [comment]
This issue needs to be split into 3 subtasks.

* #242
* #243
* #244

**Comment by thekingofcity** [comment]
It's show time!

![rmg lak6 宝山路 Baoshan_Road](https://user-images.githubusercontent.com/3353040/154654220-9c525a4e-d9fa-4ed2-a8e1-2c22dd1f8c0d.png)
![rmg lak6 宝山路 Baoshan_Road 1](https://user-images.githubusercontent.com/3353040/154654207-4e19269d-b916-4683-80d6-e44dc7e36b7a.png)
![rmg wbtv 中山公园 Zhongshan_Park](https://user-images.githubusercontent.com/3353040/154654223-6c572b8b-dca9-4d26-a444-e79578318675.png)

**Comment by wongchito** [comment]
Amazing work! Looking forward to V5 release. 🙂

**Comment by thekingofcity** [comment]
Co-line should be a working feature with several months of tweaking, feel free to open issues if you find something inappropriate.
