### ISSUE TITLE
上海地铁风格其他的转乘样式

### ISSUE THREAD

**Issue by 203IhzElttil** [railmapgen/rmg#568]
图源贵道蕉通微博
可以在系统外换乘选项中加一个功能：去掉转乘2字并且把单线车站样式改为换乘样式（对于车内单线示意图）
![image](https://github.com/railmapgen/rmg/assets/106796352/1456f7f6-8eae-44c3-a23f-7ac3986d9b29)
![image](https://github.com/railmapgen/rmg/assets/106796352/1632b259-3860-41d0-a1e8-cc4d540cbb32)

**Comment by thekingofcity** [comment]
Regarding changes in the indoor canvas, there are some inconsistencies in the out-of-system transfer between Maglev and Suzhou Rail Transit. The station icon for Pudong International Airport is the same as other non-transfer stations, but Huaqiao uses the black wide interchange icon.

I would consider this as a mistake instead of a brand-new design/classification and don't believe an update is necessary ):
